# -*- coding: utf-8 -*-
"""EDA REPORT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WKaqw1OvmHPl5e6ylo9lfZSVY7FWrnsb
"""

from google.colab import files

uploaded = files.upload()

import os

print(os.listdir())

import pandas as pd

df = pd.read_csv('marketing_campaign_performance_10000.csv')

print(df.head())

print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

channel_roi = df.groupby('Channel')['ROI'].mean().sort_values(ascending=False)

print(channel_roi)

revenue = df.groupby('Channel')['Revenue_USD'].sum().sort_values(ascending=False)

print(revenue)

df['ConversionRate'] = (
    df['Conversions'] / df['Clicks']
) * 100

conversion = (
    df.groupby('Channel')['ConversionRate']
    .mean()
    .sort_values(ascending=False)
)

print(conversion)

import matplotlib.pyplot as plt

funnel = [
    df['Impressions'].sum(),
    df['Clicks'].sum(),
    df['Leads'].sum(),
    df['Conversions'].sum()
]

labels = [
    'Impressions',
    'Clicks',
    'Leads',
    'Conversions'
]

plt.figure(figsize=(8,5))
plt.plot(labels, funnel, marker='o')
plt.title('Marketing Funnel Analysis')
plt.ylabel('Count')
plt.show()

channel_roi.plot(kind='bar')

plt.title('Average ROI by Marketing Channel')
plt.ylabel('ROI')
plt.show()

print(channel_roi)

print(revenue)

print(conversion)